
FROM gradle:8-jdk17 AS builder

WORKDIR /build

COPY . .

RUN chmod +x gradlew
RUN ./gradlew build --no-daemon

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=builder /build/build/libs/FlowAndChannelsTest-1.0-SNAPSHOT.jar app.jar

CMD ["java", "-jar", "app.jar"]
